name: Build Docker Image
on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: mcai4gl2/ice-helloworld
          tag: latest
          registry: docker.io
          dockerfile: ice-helloworld/Dockerfile
          directory: ice-helloworld
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image for C++ Client
        with:
          image: mcai4gl2/ice-helloworld-cpp-client
          tag: latest
          registry: docker.io
          dockerfile: ice-helloworld-cpp-client/Dockerfile
          directory: ice-helloworld-cpp-client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
