name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build Ice
          run: docker build -f ice-helloworld/Dockerfile ice-helloworld/
        - name: Build Ice C++ Client
          run: docker build -f ice-helloworld-cpp-client/Dockerfile ice-helloworld-cpp-client/
