name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build Ice
          run: docker build -f ice-helloworld/Dockerfile ice-helloworld/

