name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build Ice
          run: docker image build -f ice-helloworld/Dockerfile ice-helloword/

